version: 1.0.{build}
branches:
  only:
  - master
  - develop
image: Visual Studio 2019
configuration: Release
platform: Any CPU
environment:
  NUGET_API_KEY:
    secure: JQe2N9V5L/R+8ivK8QhZEQxgae1dPopyLyaVBs4m+ki5bb7BgIZEmzNWx4p3oAbEHpc+o9vnex0tWSujhbgjNrjVbmK+0aifkCyO1n+LUuw=
before_build:
- ps: dotnet restore GithubActionsTest/GithubActionsTest.sln
build:
  project: GithubActionsTest/GithubActionsTest.sln
  verbosity: minimal
artifacts:
- path: .\**\*.nupkg
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: MY9CI5+u+mwEe4G/qdR14A==
  skip_symbols: true
  artifact: nuget
  on:
    branch: master
