trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: "GithubActionsTest/GithubActionsTest.sln"
  projectToPackPath: "GithubActionsTest/ClassLibrary1/ClassLibrary1.csproj"

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(solutionPath)'
    arguments: '--configuration  $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '$(solutionPath)'
    arguments: '--configuration  $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: '$(projectToPackPath)'
    nobuild: true
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- script: dotnet nuget push $(build.artifactstagingdirectory)/*.nupkg -k $(NUGET_API_KEY) -s https://api.nuget.org/v3/index.json
  displayName: push to nuget
